### ISSUE TITLE
Update network diagrams

### ISSUE THREAD

**Issue by deadbok** [deadbok/project_network#3]
Network diagrams need to be updated with the internet connection on ROUTER-EXT.

**Comment by deadbok** [comment]
Fixed in the martin-dev branch.

**Comment by human123monkey** [comment]
Fixed in https://github.com/deadbok/project_network/commit/979c7d6864d952e6504bacff75c4e6d0c5ef5a2a

**Comment by deadbok** [comment]
Reopening since the changes have not been pushed to the `master` branch yet.

**Comment by deadbok** [comment]
Fixed in 979c7d6 again

**Comment by deadbok** [comment]
Fixed in 979c7d6 again :-)
